name: "Build Preview Deployment"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-preview:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          
      - uses: "pnpm/action-setup@v4"

      - uses: "actions/setup-node@v4"
        with:
          cache: "pnpm"
          node-version: 20

      - run: "pnpm install"
      
      - run: "pnpm run build"
        env:
          CI_ENV: preview
          GITHUB_PR_HEAD_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
      
      - run: |
          cp _headers build/
          cp _redirects build/

      - uses: "actions/upload-artifact@v4"
        with:
          name: "preview-build"
          path: "build"
