name: "Production Deployment"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      
      - uses: "pnpm/action-setup@v4"

      - uses: "actions/setup-node@v4"
        with:
          cache: "pnpm"
          node-version: 20

      - run: "pnpm install"
      
      - run: "pnpm run build"
        env:
          CI_ENV: production
      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"    
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}    